import Navbar from "@/components/Navbar"
import './globals.css'

export const metadata = {
  title: 'Todo App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-zinc-400">
        <div className="max-w-3xl mx-auto p-4">
          <Navbar />
          <div className="mt-8">
            {children}
          </div>
        </div>
      </body>
    </html>
  )
}
